server:
  port: 3300

##############################################
#
# thymeleaf静态资源配置
#
##############################################
# 默认路径
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
